--- 
:backgroundrb: 
  :ip: localhost
  :port: 11006
  :environment: development
:schedules:
  :housekeeper_worker:
    :clean:
      :trigger_args: 0 * */24 * * *
  :client_checker_worker:
    :check:
      :trigger_args: 0 * * * * *
